version: '3'

services:
  bot:
    build:
      context: .
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    depends_on:
      - redis
    networks:
      - dolphin-network
    volumes:
      - /home/cye/AI/models:/usr/src/app/models

  redis:
    hostname: dolphin-redis
    restart: always
    image: "redis:latest"
    networks:
      - dolphin-network

networks:
  dolphin-network:
    driver: bridge
